apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-9308"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-9308"
  template:
    metadata:
      labels:
        app: "myakscluster-9308"
    spec:
      containers:
        - name: "myakscluster-9308"
          image: "myacr12dec.azurecr.io/myakscluster"
          ports:
          - containerPort: 5000